### ISSUE TITLE
Compatibilities

### ISSUE THREAD

**Issue by AlphaLeoli** [ebicep/ChatPlus#20]
make the mod compatible with [chat logs](https://modrinth.com/mod/permanent-chatlogs) and with [hide chat](https://modrinth.com/mod/betterhiddenchat)

**Comment by AlphaLeoli** [comment]
oh and i think [symbol chat](https://modrinth.com/mod/symbol-chat) has incompatibility with the buttons in the bottom right

**Comment by ebicep** [comment]
> [chat logs](https://modrinth.com/mod/permanent-chatlogs)

Fixed in the next future release

> [hide chat](https://modrinth.com/mod/betterhiddenchat)

Since ChatPlus renders the chat in a custom manner, this feature will be implemented in a customized way in the next future release.

> oh and i think [symbol chat](https://modrinth.com/mod/symbol-chat) has incompatibility with the buttons in the bottom right

This was reported and fixed in https://github.com/ebicep/ChatPlus/issues/3 
Below shows that it works (1.21.1) and I recommend having this Symbol Chat Config option enabled so you don't need to keep reclicking the ChatPlus button, "translator" in this case.
![image](https://github.com/user-attachments/assets/cad6fcdd-194c-4b3e-94cb-2482e1f54605)
![image](https://github.com/user-attachments/assets/edd783a9-ad8b-4651-a189-c1a41740a659)

**Comment by ebicep** [comment]
Fixed/Added in v2.0.0
