### ISSUE TITLE
Scrollbar does not render

### ISSUE THREAD

**Issue by Pablete1234** [ebicep/ChatPlus#22]
Scroll bar in the chat window can be configured width-wise and color-wise, but even making it extreme (15px and bright red) it is nowhere to be found

**Comment by ebicep** [comment]
Setting the scroll bar to extreme values was never intended and the field was left open for user control but a slider will replace it.
Using 15px also works for me so I either randomly fixed it since the last release or perhaps you don't have enough messages so the bar doesn't render.
![image](https://github.com/user-attachments/assets/244ee626-b2ad-4c5c-9898-865ac2762073)

**Comment by Pablete1234** [comment]
>  Setting the scroll bar to extreme values was never intended 
To be clear,  i don't want it to use extreme values, i just set it to extreme value to try to find it

![image](https://github.com/user-attachments/assets/765157ff-2466-4b4e-bc59-e7e853414625)
I filled the chat with simple F3+Q and scrolled a bit:

![image](https://github.com/user-attachments/assets/7d5ef602-6e6a-43ae-b73d-aaa71880fdf8)

no scrollbar.

I'll re-test when the new version is released, maybe it was fixed in dev branch

**Comment by ebicep** [comment]
Can you confirm this is fixed in v2.0.0

**Comment by Pablete1234** [comment]
can confirm this is solved
